FROM logickee/openbox-poe-seat-apps

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

RUN apt --fix-broken install -qy ./google-chrome-stable_current_amd64.deb

RUN rm -rf google-chrome-stable_current_amd64.deb
